spring:
  application:
    name: payment-project
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080